name: Setup Dev Infrastructure

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials from Production Account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ap-southeast-1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize
        id: init
        working-directory: ./infra
        run: terraform init -backend-config=backend/dev.conf

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        working-directory: ./infra
        run: terraform apply --auto-approve
        env:
          TF_VAR_ENV: dev
          TF_VAR_VERSION: dev
          TF_VAR_DOMAIN: "*.qro-dev.equipweb.biz"
